package: demo_community
version: '1.2.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/demo_community

page:
    title: 'Community-Demo'
    perm: demo_community[]
    pjax: true
    subpages:
        description: { title: 'Community-Demo' }

requires:
    packages:
        backup: '>=2.0.3'
        structure/content: '>=2.1.0'
        markitup: '>=3.0.0'
        phpmailer: '>=2.1.0'
        yform: '>=2.0'
        yform/geo: '>=2.0'
        ycom: '>=1.0'
    redaxo: '>=5.2.0'
